"""added designation table

Revision ID: 9ce2e76c210e
Revises: 15b0d0fc4adb
Create Date: 2024-10-09 18:37:59.905808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce2e76c210e'
down_revision: Union[str, None] = '15b0d0fc4adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_designation_id'), 'designation', ['id'], unique=False)
    op.add_column('users', sa.Column('job_title_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'designation', ['job_title_id'], ['id'])
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'job_title_id')
    op.drop_index(op.f('ix_designation_id'), table_name='designation')
    op.drop_table('designation')
    # ### end Alembic commands ###
